Repository backtothefuture-team/bagToTheFuture-frontend, pull requests merged in 2024-05, with the labels that each got.

#86 design: 닉네임, 환불 정보 UI 제거
  lib/screen/sign_up/components/sign_up_form.dart
Labels: 🎨 design

#89 feat: 프로필 편집 화면
  lib/config/common/sized_box_values.dart
  lib/main.dart
  lib/screen/my_page/components/my_page/user_widget.dart
  lib/screen/my_page/edit_my_profile_screen.dart
  lib/screen/my_page/refund_info_screen.dart
  lib/screen/view_model/edit_my_profile_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: 🌱 feat, 🎨 design

#97 design: 93 bottom navigation
  assets/images/ic_activated_home.svg
  assets/images/ic_activated_my_favorite.svg
  assets/images/ic_activated_my_page.svg
  assets/images/ic_home.svg
  assets/images/ic_my_favorite.svg
  assets/images/ic_my_page.svg
  lib/design/svg_icon.dart
  lib/screen/my_bottom_navigation.dart
Labels: 🎨 design

#98 refactor: 95 refactor reset pw
  lib/main.dart
  lib/screen/sign_up/reset_pw_screen.dart
  lib/screen/view_model/reset_pw_view_model.dart
Labels: 🔨 refactor

#92 feat: splash UI
  assets/images/ic_bttf_text_logo.svg
  ios/Podfile
  ios/Podfile.lock
  lib/design/svg_icon.dart
  lib/main.dart
  lib/screen/sign_in/sign_in_screen.dart
  lib/screen/splash/first_splash_screen.dart
  lib/screen/splash/second_splash_screen.dart
  lib/screen/view_model/setting_view_model.dart
Labels: 🌱 feat

#91 design: store review list ui
  lib/design/svg_icon.dart
  lib/screen/home/components/store_info/order_button_widget.dart
  lib/screen/home/components/store_info/store_info_widget.dart
  lib/screen/home/store_review_list.dart
Labels: 🌱 feat, 🎨 design

#88 design: 자주 묻는 질문 내용 변경
  lib/data/source/qna_data.dart
  lib/screen/my_page/customer_service_screen.dart
Labels: 🎨 design

#84 feat: 리뷰 관리 UI 개발
  assets/images/ic_edit.svg
  assets/images/ic_trash.svg
  lib/design/svg_icon.dart
  lib/screen/my_page/components/my_page/user_widget.dart
  lib/screen/my_page/my_review_list_screen.dart
  lib/screen/my_page/review_list_screen.dart
Labels: 🌱 feat, 🎨 design
