Repository backtothefuture-team/bagToTheFuture-frontend, pull requests merged in 2024-04, with the labels that each got.

#59 fix: 카카오/네이버 로그인 이슈 확인 및 해결
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/profile/AndroidManifest.xml
  devtools_options.yaml
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/config/custom_snack_bar.dart
  lib/config/di.dart
  lib/config/social_sign_in.dart
  lib/main.dart
  lib/screen/my_page/components/sign_out.dart
  lib/screen/sign_in/sign_in_screen.dart
  lib/screen/sign_in/sign_in_view_model.dart
Labels: ⚒️ fix

#63 feat: BTTF-12-kakao-channel
  android/app/src/main/AndroidManifest.xml
  assets/images/ic_headset_microphone.svg
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/config/constants.dart
  lib/config/my_text.dart
  lib/data/model/qna_model.dart
  lib/data/source/qna_data.dart
  lib/design/color_styles.dart
  lib/design/svg_icon.dart
  lib/main.dart
  lib/screen/my_page/components/my_page_menu_widget.dart
  lib/screen/my_page/customer_service_screen.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: 🌱 feat

#62 feat: BTTF-13-order-screen-UI
  lib/design/color_styles.dart
  lib/main.dart
  lib/screen/home/components/order/order_list_widget.dart
  lib/screen/home/components/order/pay_button.dart
  lib/screen/home/components/order/pick_up_time_info.dart
  lib/screen/home/components/store_info/menu_widget.dart
  lib/screen/home/components/store_info/order_button_widget.dart
  lib/screen/home/components/store_info/store_info_widget.dart
  lib/screen/home/components/store_info/surprise_bag_widget.dart
  lib/screen/home/order_screen.dart
  lib/screen/home/store_info_screen.dart
  lib/screen/view_model/store_info_view_model.dart
Labels: 🌱 feat

#64 feat: BTTF-15-reservation-dialog-ui
  assets/images/btf_logo.png
  assets/images/logo.svg
  lib/config/common/sized_box_values.dart
  lib/design/svg_icon.dart
  lib/screen/home/components/home/store_list_widget.dart
  lib/screen/home/components/order/pay_button.dart
  lib/screen/home/components/store_info/store_info_widget.dart
  lib/screen/home/store_info_screen.dart
  lib/screen/my_page/components/user_profile/user_profile_image.dart
  lib/screen/my_page/components/user_profile/user_profile_widget.dart
  lib/screen/sign_in/sign_in_screen.dart
  lib/screen/view_model/store_info_view_model.dart
Labels: 🌱 feat

#66 design: BTTF-16-my-page-ui
  assets/images/comment.svg
  assets/images/info.svg
  assets/images/order.svg
  assets/images/question.svg
  assets/images/setting.svg
  lib/design/svg_icon.dart
  lib/screen/home/order_detail_screen.dart
  lib/screen/my_page/components/my_page/menu_widget.dart
  lib/screen/my_page/components/my_page/recent_order.dart
  lib/screen/my_page/components/my_page/user_widget.dart
  lib/screen/my_page/components/my_recent_order_list.dart
  lib/screen/my_page/components/sign_out.dart
  lib/screen/my_page/components/user_profile/user_profile_image.dart
  lib/screen/my_page/components/user_profile/user_profile_widget.dart
  lib/screen/my_page/my_page_screen.dart
  lib/screen/my_page/order_detail_screen.dart
  lib/screen/my_page/order_list_screen.dart
  lib/screen/my_page/review_list_screen.dart
  lib/screen/my_page/setting_screen.dart
  lib/screen/my_page/user_profile_detail_screen.dart
Labels: 🌱 feat

#67 feat: 서비스 피드백 구현
  assets/images/ic_down_arrow_1.svg
  assets/images/ic_right_arrow.svg
  assets/images/ic_up_arrow_1.svg
  assets/images/service_feedback.svg
  lib/data/model/qna_model.dart
  lib/data/source/qna_data.dart
  lib/design/color_styles.dart
  lib/design/svg_icon.dart
  lib/screen/my_page/customer_service_screen.dart
Labels: 🌱 feat, 🎨 design

#65 design: BTTF-14-sign-up-UI
  assets/images/ic_checked.svg
  assets/images/ic_unchecked.svg
  lib/config/constants.dart
  lib/config/custom_app_bar.dart
  lib/config/user_info_text_form_field.dart
  lib/config/validation_check.dart
  lib/design/svg_icon.dart
  lib/main.dart
  lib/screen/sign_in/sign_in_screen.dart
  lib/screen/sign_up/components/sign_up_form.dart
  lib/screen/sign_up/components/term_of_use.dart
  lib/screen/sign_up/components/terms_of_use.dart
  lib/screen/sign_up/sign_up_screen.dart
  lib/screen/view_model/sign_in_view_model.dart
  lib/screen/view_model/sign_up_view_model.dart
Labels: 🎨 design

#70 feat: 설정 화면 구현
  android/app/src/main/AndroidManifest.xml
  assets/images/ic_disabled_toggle.svg
  assets/images/ic_enabled_toggle.svg
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/design/svg_icon.dart
  lib/main.dart
  lib/screen/my_page/setting_screen.dart
  lib/screen/view_model/setting_view_model.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: 🌱 feat, 🎨 design

#76 modify: 생년월일에 대한 유효성 검사 제거
  lib/screen/sign_up/components/sign_up_form.dart
Labels: ⚒️ fix

#69 fix: change order modal logo
  assets/images/order_logo.svg
  lib/design/svg_icon.dart
  lib/screen/home/store_info_screen.dart
Labels: ⚒️ fix

#72 modify: 이메일 인증 api 수정
  lib/data/model/email_auth_response.dart
  lib/data/model/get_response.dart
  lib/data/model/response_data.dart
  lib/data/model/sign_in_response.dart
  lib/data/model/token_data_model.dart
  lib/data/source/rest_client.dart
  lib/screen/view_model/email_auth_view_model.dart
Labels: ⚒️ fix

#79 Feat/fcm
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/settings.gradle
  firebase.json
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info.plist
  lib/firebase_options.dart
  lib/main.dart
  lib/screen/home/home_screen.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner/GoogleService-Info.plist
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: 🌱 feat

#80 feat: feature/BTTF-24-write-review-ui
  android/app/src/main/AndroidManifest.xml
  assets/images/ic_back_button.svg
  assets/images/ic_camera.svg
  assets/images/ic_close_button.svg
  assets/images/ic_comment.svg
  assets/images/ic_gallery.svg
  assets/images/ic_info.svg
  assets/images/ic_logo.svg
  assets/images/ic_order.svg
  assets/images/ic_order_logo.svg
  assets/images/ic_question.svg
  assets/images/ic_review_left_star.svg
  assets/images/ic_review_right_star.svg
  assets/images/ic_setting.svg
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/design/svg_icon.dart
  lib/screen/home/components/store_info/store_info_widget.dart
  lib/screen/my_page/components/my_page/in_progress_order.dart
  lib/screen/my_page/components/my_page/recent_order.dart
  lib/screen/my_page/components/my_page/user_widget.dart
  lib/screen/my_page/my_page_screen.dart
  lib/screen/my_page/order_list_screen.dart
  lib/screen/my_page/write_review_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: 🌱 feat, 🎨 design

#82 feat: 찜 목록 UI
  assets/images/ic_purple_bag.svg
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/config/common/sized_box_values.dart
  lib/data/model/store_card_info_model.dart
  lib/data/source/rest_client.dart
  lib/data/source/store_card_info_data.dart
  lib/design/svg_icon.dart
  lib/screen/favorite_list/components/store_card_widget.dart
  lib/screen/favorite_list/favorite_list_screen.dart
  lib/screen/my_bottom_navigation.dart
  lib/screen/wish_list/wish_list_screen.dart
  pubspec.lock
Labels: 🌱 feat, 🎨 design
